//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sauron.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sauron.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à /cgi-bin/configManager.cgi?action=getConfig&amp;name={0}.
        /// </summary>
        public static string GetConfigUrl {
            get {
                return ResourceManager.GetString("GetConfigUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à /cgi-bin/{0}.cgi?action=getStatus&amp;channel={1}.
        /// </summary>
        public static string GetStatusUrl {
            get {
                return ResourceManager.GetString("GetStatusUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Move down.
        /// </summary>
        public static string MoveDownCommandToolTip {
            get {
                return ResourceManager.GetString("MoveDownCommandToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Move left.
        /// </summary>
        public static string MoveLeftCommandToolTip {
            get {
                return ResourceManager.GetString("MoveLeftCommandToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Move left and down.
        /// </summary>
        public static string MoveLeftDownCommandToolTip {
            get {
                return ResourceManager.GetString("MoveLeftDownCommandToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Move left and up.
        /// </summary>
        public static string MoveLeftUpCommandToolTip {
            get {
                return ResourceManager.GetString("MoveLeftUpCommandToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Move right.
        /// </summary>
        public static string MoveRightCommandToolTip {
            get {
                return ResourceManager.GetString("MoveRightCommandToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Move right and down.
        /// </summary>
        public static string MoveRightDownCommandToolTip {
            get {
                return ResourceManager.GetString("MoveRightDownCommandToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Move right and up.
        /// </summary>
        public static string MoveRightUpCommandToolTip {
            get {
                return ResourceManager.GetString("MoveRightUpCommandToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Moves.
        /// </summary>
        public static string MovesGroupBoxLabel {
            get {
                return ResourceManager.GetString("MovesGroupBoxLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Move up.
        /// </summary>
        public static string MoveUpCommandToolTip {
            get {
                return ResourceManager.GetString("MoveUpCommandToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à /cam/realmonitor?channel=1&amp;subtype=0.
        /// </summary>
        public static string VideoUrl {
            get {
                return ResourceManager.GetString("VideoUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Zoom.
        /// </summary>
        public static string ZoomGroupBoxLabel {
            get {
                return ResourceManager.GetString("ZoomGroupBoxLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Zoom out.
        /// </summary>
        public static string ZoomTeleCommandToolTip {
            get {
                return ResourceManager.GetString("ZoomTeleCommandToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Zoom in.
        /// </summary>
        public static string ZoomWideCommandToolTip {
            get {
                return ResourceManager.GetString("ZoomWideCommandToolTip", resourceCulture);
            }
        }
    }
}
